"""
export_samples.py
Evaluation support for Phase 4 (comparison #2 in docs/DESIGN.md:
"detection-only vs. detection + narrative").

Picks one narrated incident per ground-truth attack scenario (A/B/C) and writes
them to a committed markdown file, so the report has stable, quotable evidence
that the narrative layer adds something over a raw anomaly list.

Usage:
    python src/export_samples.py
"""

import argparse
import json
from pathlib import Path

import pandas as pd

from config import DEFAULT_INCIDENTS_PATH, RAW_DATA_DIR

SCENARIO_NAMES = {
    "A": "Brute force -> successful login -> privilege escalation",
    "B": "Impossible travel (same account, two distant source IPs)",
    "C": "Account enumeration (many usernames probed from one source IP)",
}


def load_ground_truth(path: str) -> pd.DataFrame:
    gt = pd.read_csv(path)
    gt["timestamp"] = pd.to_datetime(gt["timestamp"])
    return gt


def scenario_of(incident: dict, ground_truth: pd.DataFrame) -> str | None:
    """Which attack scenario does this incident overlap, if any?

    Matched on (timestamp, user) pairs, the same key the ground-truth file uses.
    """
    keys = {(pd.to_datetime(e["timestamp"]), str(e["user"])) for e in incident["events"]}
    hits = ground_truth[
        ground_truth.apply(lambda r: (r["timestamp"], str(r["user"])) in keys, axis=1)
    ]
    if hits.empty:
        return None
    return hits["scenario"].mode().iloc[0]


def pick_samples(incidents: list[dict], ground_truth: pd.DataFrame) -> dict[str, dict]:
    """One narrated incident per scenario -- the largest, as the richest example."""
    best: dict[str, dict] = {}
    for incident in incidents:
        if not incident.get("narrative"):
            continue
        scenario = scenario_of(incident, ground_truth)
        if scenario is None:
            continue
        if scenario not in best or incident["event_count"] > best[scenario]["event_count"]:
            best[scenario] = incident
    return best


def render(samples: dict[str, dict]) -> str:
    lines = [
        "# Sample Attack Narratives",
        "",
        "Generated by `src/export_samples.py` from `data/processed/incidents.json`.",
        "One incident per ground-truth attack scenario. Technique IDs come from the",
        "grounded lookup in `src/mitre_mapping.py` -- the LLM is given them, never asked",
        "to invent them.",
        "",
    ]
    for scenario in sorted(samples):
        incident = samples[scenario]
        lines += [
            f"## Scenario {scenario} — {SCENARIO_NAMES.get(scenario, 'unknown')}",
            "",
            f"- **Incident ID:** {incident['incident_id']}",
            f"- **Severity:** {incident['severity']}",
            f"- **Window:** {incident['start']} → {incident['end']}",
            f"- **Users:** {', '.join(incident.get('users', [])) or 'n/a'}",
            f"- **Source IPs:** {', '.join(incident.get('source_ips', [])) or 'n/a'}",
            "- **MITRE techniques (grounded):** " + (", ".join(
                f"{t['technique_id']} {t['technique_name']}"
                for t in incident.get("mitre_techniques", [])) or "none"),
            "",
            "### Raw anomalous events (what detection alone gives you)",
            "",
            "```",
            *[f"[{e['timestamp']}] user={e['user']} src={e['source_ip']} : {e['message']}"
              for e in incident["events"]],
            "```",
            "",
            "### Generated narrative (what the LLM layer adds)",
            "",
            incident["narrative"],
            "",
        ]
    return "\n".join(lines)


def main(incidents_path: str, ground_truth_path: str, output_path: str) -> None:
    incidents = json.loads(Path(incidents_path).read_text())
    ground_truth = load_ground_truth(ground_truth_path)

    samples = pick_samples(incidents, ground_truth)
    missing = sorted(set(SCENARIO_NAMES) - set(samples))
    if missing:
        print(f"WARNING: no narrated incident found for scenario(s): {', '.join(missing)}")

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(render(samples))
    print(f"Wrote {len(samples)} sample narratives -> {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export one sample narrative per attack scenario.")
    parser.add_argument("--incidents", default=DEFAULT_INCIDENTS_PATH)
    parser.add_argument("--ground-truth", default=f"{RAW_DATA_DIR}/ground_truth.csv")
    parser.add_argument("--output", default="results/sample_narratives.md")
    args = parser.parse_args()

    main(args.incidents, args.ground_truth, args.output)
